version: '3.8'

services:
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        volumes:
            - db-siscom:/data/db

volumes:
    db-siscom:
